version: '3.8'

services:
  external_service:
    image: michelgl/warrantymicroservices:external_service
    command: uvicorn external_service.app.external_service:app --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - USER_SERVICE_URL=http://user_service:8002
      - DEFECT_SERVICE_URL=http://defect_service:8003

  user_service:
    image: michelgl/warrantymicroservices:user_service
    command: uvicorn user_service.app.user_service:app --reload --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  defect_service:
    image: michelgl/warrantymicroservices:defect_service
    command: uvicorn defect_service.app.defect_service:app --reload --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"